<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Citas\" />
    <Folder Include="Mapeos\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediTrack.Dominio\MediTrack.Dominio.csproj" />
    <ProjectReference Include="..\MediTrack.Infraestructura\MediTrack.Infraestructura.csproj" />
  </ItemGroup>

</Project>
