<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
    <Folder Include="Extensiones\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediTrack.Aplicacion\MediTrack.Aplicacion.csproj" />
    <ProjectReference Include="..\MediTrack.Dominio\MediTrack.Dominio.csproj" />
    <ProjectReference Include="..\MediTrack.Infraestructura\MediTrack.Infraestructura.csproj" />
  </ItemGroup>

</Project>
