<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controladores\" />
    <Folder Include="Middlewares\" />
    <Folder Include="Extensiones\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediTrack.Aplicacion\MediTrack.Aplicacion.csproj" />
    <ProjectReference Include="..\MediTrack.Infraestructura\MediTrack.Infraestructura.csproj" />
  </ItemGroup>

</Project>
